[package]
name = "random_files"
version = "0.1.0"
edition = "2021"

[dependencies]
env_logger = "0.11"
log = "0.4"
mime_guess = "2.0"
rand = "0.8"
tokio = { version = "1", features = ["full"] }
warp = "0.3"
